<div class="grid w-full max-w-[750px] grid-cols-2 gap-2 sm:flex sm:w-auto sm:max-w-none sm:items-center sm:justify-start sm:gap-4">
    <a aria-current="{{ $active === 'manga' ? 'page' : null }}" class="flex min-h-12 items-center justify-center rounded-2xl border px-3 py-3 text-center text-sm leading-none font-semibold whitespace-nowrap transition-all duration-200 [@media(max-width:359px)]:min-h-11 [@media(max-width:359px)]:px-2 [@media(max-width:359px)]:text-[11px] sm:rounded-[32px] sm:border-0 sm:px-3 sm:py-1.5 sm:text-base sm:leading-normal @if($active === 'manga') border-lav-400 bg-lav-500/18 text-txt-primary shadow-[0_10px_30px_rgba(211,115,255,0.16)] sm:bg-btn-primary sm:text-txt-inverse sm:shadow-none @else border-white/8 bg-bgc-layer-semi-neutral/70 text-txt-secondary hover:border-white/14 hover:text-txt-primary sm:bg-bgc-layer-semi-neutral sm:text-txt-primary @endif" href="{{ route('leaderboard.manga') }}" data-discover="true"><span class="sm:hidden">Top Truyện</span><span class="hidden sm:inline">Top Truyện hentai</span></a>

    <a aria-current="{{ $active === 'member' ? 'page' : null }}" class="flex min-h-12 items-center justify-center rounded-2xl border px-3 py-3 text-center text-sm leading-none font-semibold whitespace-nowrap transition-all duration-200 [@media(max-width:359px)]:min-h-11 [@media(max-width:359px)]:px-2 [@media(max-width:359px)]:text-[11px] sm:rounded-[32px] sm:border-0 sm:px-3 sm:py-1.5 sm:text-base sm:leading-normal @if($active === 'member') border-lav-400 bg-lav-500/18 text-txt-primary shadow-[0_10px_30px_rgba(211,115,255,0.16)] sm:bg-btn-primary sm:text-txt-inverse sm:shadow-none @else border-white/8 bg-bgc-layer-semi-neutral/70 text-txt-secondary hover:border-white/14 hover:text-txt-primary sm:bg-bgc-layer-semi-neutral sm:text-txt-primary @endif" href="{{ route('leaderboard.member') }}" data-discover="true"><span class="sm:hidden">Thành viên</span><span class="hidden sm:inline">Thánh Lọ Bảng</span></a>

    <a aria-current="{{ $active === 'waifu' ? 'page' : null }}" class="flex min-h-12 items-center justify-center rounded-2xl border px-3 py-3 text-center text-sm leading-none font-semibold whitespace-nowrap transition-all duration-200 [@media(max-width:359px)]:min-h-11 [@media(max-width:359px)]:px-2 [@media(max-width:359px)]:text-[11px] sm:rounded-[32px] sm:border-0 sm:px-3 sm:py-1.5 sm:text-base sm:leading-normal @if($active === 'waifu') border-lav-400 bg-lav-500/18 text-txt-primary shadow-[0_10px_30px_rgba(211,115,255,0.16)] sm:bg-btn-primary sm:text-txt-inverse sm:shadow-none @else border-white/8 bg-bgc-layer-semi-neutral/70 text-txt-secondary hover:border-white/14 hover:text-txt-primary sm:bg-bgc-layer-semi-neutral sm:text-txt-primary @endif" href="{{ route('leaderboard.waifu') }}" data-discover="true"><span class="sm:hidden">Harem</span><span class="hidden sm:inline">Top Harem</span></a>

    <a aria-current="{{ $active === 'translator' ? 'page' : null }}" class="flex min-h-12 items-center justify-center rounded-2xl border px-3 py-3 text-center text-sm leading-none font-semibold whitespace-nowrap transition-all duration-200 [@media(max-width:359px)]:min-h-11 [@media(max-width:359px)]:px-2 [@media(max-width:359px)]:text-[11px] sm:rounded-[32px] sm:border-0 sm:px-3 sm:py-1.5 sm:text-base sm:leading-normal @if($active === 'translator') border-lav-400 bg-lav-500/18 text-txt-primary shadow-[0_10px_30px_rgba(211,115,255,0.16)] sm:bg-btn-primary sm:text-txt-inverse sm:shadow-none @else border-white/8 bg-bgc-layer-semi-neutral/70 text-txt-secondary hover:border-white/14 hover:text-txt-primary sm:bg-bgc-layer-semi-neutral sm:text-txt-primary @endif" href="{{ route('leaderboard.translator') }}" data-discover="true"><span class="sm:hidden">Dịch giả</span><span class="hidden sm:inline">BXH Dịch Giả</span></a>
</div>
